In [160]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
sns.set()

In [161]:
raw_data = pd.read_csv('train.csv')

In [295]:
raw_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [163]:
pd.options.display.max_columns  = None
pd.options.display.max_rows = None

In [164]:
raw_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [165]:
data_c = raw_data.copy()

In [166]:
data_c.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [167]:
data_c.columns.values

array(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'], dtype=object)

In [168]:
temp = ['PassengerId','Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked','Survived']
data_c = data_c[temp]
data_c.head()

PassengerId  Pclass                                               Name  \
0            1       3                            Braund, Mr. Owen Harris   
1            2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3       3                             Heikkinen, Miss. Laina   
3            4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [169]:
pclass = data_c['Pclass']


In [170]:
pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [171]:
df =pd.get_dummies(pclass,drop_first= True)
df

2  3
0    0  1
1    0  0
2    0  1
3    0  0
4    0  1
5    0  1
6    0  0
7    0  1
8    0  1
9    1  0
10   0  1
11   0  0
12   0  1
13   0  1
14   0  1
15   1  0
16   0  1
17   1  0
18   0  1
19   0  1
20   1  0
21   1  0
22   0  1
23   0  0
24   0  1
25   0  1
26   0  1
27   0  0
28   0  1
29   0  1
30   0  0
31   0  0
32   0  1
33   1  0
34   0  0
35   0  0
36   0  1
37   0  1
38   0  1
39   0  1
40   0  1
41   1  0
42   0  1
43   1  0
44   0  1
45   0  1
46   0  1
47   0  1
48   0  1
49   0  1
50   0  1
51   0  1
52   0  0
53   1  0
54   0  0
55   0  0
56   1  0
57   0  1
58   1  0
59   0  1
60   0  1
61   0  0
62   0  0
63   0  1
64   0  0
65   0  1
66   1  0
67   0  1
68   0  1
69   0  1
70   1  0
71   0  1
72   1  0
73   0  1
74   0  1
75   0  1
76   0  1
77   0  1
78   1  0
79   0  1
80   0  1
81   0  1
82   0  1
83   0  0
84   1  0
85   0  1
86   0  1
87   0  1
88   0  0
89   0  1
90   0  1
91   0  1
92   0  0
93   0  1
94   0  1
95   0  1
96   0  0
97   0  0
98   1  0
99   1  0
100  0  1
101  0  1
102  0  0
103  0  1
104  0  1
105  0  1
106  0  1
107  0  1
108  0  1
109  0  1
110  0  0
111  0  1
112  0  1
113  0  1
114  0  1
115  0  1
116  0  1
117  1  0
118  0  0
119  0  1
120  1  0
121  0  1
122  1  0
123  1  0
124  0  0
125  0  1
126  0  1
127  0  1
128  0  1
129  0  1
130  0  1
131  0  1
132  0  1
133  1  0
134  1  0
135  1  0
136  0  0
137  0  0
138  0  1
139  0  0
140  0  1
141  0  1
142  0  1
143  0  1
144  1  0
145  1  0
146  0  1
147  0  1
148  1  0
149  1  0
150  1  0
151  0  0
152  0  1
153  0  1
154  0  1
155  0  0
156  0  1
157  0  1
158  0  1
159  0  1
160  0  1
161  1  0
162  0  1
163  0  1
164  0  1
165  0  1
166  0  0
167  0  1
168  0  0
169  0  1
170  0  0
171  0  1
172  0  1
173  0  1
174  0  0
175  0  1
176  0  1
177  0  0
178  1  0
179  0  1
180  0  1
181  1  0
182  0  1
183  1  0
184  0  1
185  0  0
186  0  1
187  0  0
188  0  1
189  0  1
190  1  0
191  1  0
192  0  1
193  1  0
194  0  0
195  0  0
196  0  1
197  0  1
198  0  1
199  1  0
200  0  1
201  0  1
202  0  1
203  0  1
204  0  1
205  0  1
206  0  1
207  0  1
208  0  1
209  0  0
210  0  1
211  1  0
212  0  1
213  1  0
214  0  1
215  0  0
216  0  1
217  1  0
218  0  0
219  1  0
220  0  1
221  1  0
222  0  1
223  0  1
224  0  0
225  0  1
226  1  0
227  0  1
228  1  0
229  0  1
230  0  0
231  0  1
232  1  0
233  0  1
234  1  0
235  0  1
236  1  0
237  1  0
238  1  0
239  1  0
240  0  1
241  0  1
242  1  0
243  0  1
244  0  1
245  0  0
246  0  1
247  1  0
248  0  0
249  1  0
250  0  1
251  0  1
252  0  0
253  0  1
254  0  1
255  0  1
256  0  0
257  0  0
258  0  0
259  1  0
260  0  1
261  0  1
262  0  0
263  0  0
264  0  1
265  1  0
266  0  1
267  0  1
268  0  0
269  0  0
270  0  0
271  0  1
272  1  0
273  0  0
274  0  1
275  0  0
276  0  1
277  1  0
278  0  1
279  0  1
280  0  1
281  0  1
282  0  1
283  0  1
284  0  0
285  0  1
286  0  1
287  0  1
288  1  0
289  0  1
290  0  0
291  0  0
292  1  0
293  0  1
294  0  1
295  0  0
296  0  1
297  0  0
298  0  0
299  0  0
300  0  1
301  0  1
302  0  1
303  1  0
304  0  1
305  0  0
306  0  0
307  0  0
308  1  0
309  0  0
310  0  0
311  0  0
312  1  0
313  0  1
314  1  0
315  0  1
316  1  0
317  1  0
318  0  0
319  0  0
320  0  1
321  0  1
322  1  0
323  1  0
324  0  1
325  0  0
326  0  1
327  1  0
328  0  1
329  0  0
330  0  1
331  0  0
332  0  0
333  0  1
334  0  0
335  0  1
336  0  0
337  0  0
338  0  1
339  0  0
340  1  0
341  0  0
342  1  0
343  1  0
344  1  0
345  1  0
346  1  0
347  0  1
348  0  1
349  0  1
350  0  1
351  0  0
352  0  1
353  0  1
354  0  1
355  0  1
356  0  0
357  1  0
358  0  1
359  0  1
360  0  1
361  1  0
362  0  1
363  0  1
364  0  1
365  0  1
366  0  0
367  0  1
368  0  1
369  0  0
370  0  0
371  0  1
372  0  1
373  0  0
374  0  1
375  0  0
376  0  1
377  0  0
378  0  1
379  0  1
380  0  0
381  0  1
382  0  1
383  0  0
384  0  1
385  1  0
386  0  1
387  1  0
388  0  1
389  1  0
390  0  0
391  0  1
392  0  1
393  0  0
394  0  1
395  0  1
396  0  1
397  1  0
398  1  0
399  

In [172]:
class_2 = df.iloc[:,0]
class_3 = df.iloc[:,1]


In [173]:
data_c.columns.values

array(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked', 'Survived'], dtype=object)

In [174]:
new_df = pd.concat([data_c,class_2,class_3],axis = 1)
new_df.head()

PassengerId  Pclass                                               Name  \
0            1       3                            Braund, Mr. Owen Harris   
1            2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3       3                             Heikkinen, Miss. Laina   
3            4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  2  3  
0         0  0  1  
1         1  0  0  
2         1  0  1  
3         1  0  0  
4         0  0  1

In [175]:
new_df.head()


PassengerId  Pclass                                               Name  \
0            1       3                            Braund, Mr. Owen Harris   
1            2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3       3                             Heikkinen, Miss. Laina   
3            4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  2  3  
0         0  0  1  
1         1  0  0  
2         1  0  1  
3         1  0  0  
4         0  0  1

In [176]:
new_df.columns.values

array(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked', 'Survived', 2, 3],
      dtype=object)

In [177]:
save_checkpoint = new_df.copy()

In [178]:
temp2 = ['Name', 2, 3,'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin',
       'Embarked', 'Survived']
df.shape


(891, 2)

In [179]:
new_df.head()

PassengerId  Pclass                                               Name  \
0            1       3                            Braund, Mr. Owen Harris   
1            2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3       3                             Heikkinen, Miss. Laina   
3            4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  2  3  
0         0  0  1  
1         1  0  0  
2         1  0  1  
3         1  0  0  
4         0  0  1

In [180]:
new_df = new_df[temp2]

In [181]:
new_df = new_df.drop('Name',axis = 1)
new_df.head()

2  3     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0  0  1    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  0  0  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  0  1  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  0  0  female  35.0      1      0            113803  53.1000  C123        S   
4  0  1    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [182]:
new_df['Sex'] = new_df['Sex'].map({'male':0,'female':1})
new_df.head()

2  3  Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0  0  1    0  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  0  0    1  38.0      1      0          PC 17599  71.2833   C85        C   
2  0  1    1  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  0  0    1  35.0      1      0            113803  53.1000  C123        S   
4  0  1    0  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [183]:
save_checkpoint.head()

PassengerId  Pclass                                               Name  \
0            1       3                            Braund, Mr. Owen Harris   
1            2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3       3                             Heikkinen, Miss. Laina   
3            4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  2  3  
0         0  0  1  
1         1  0  0  
2         1  0  1  
3         1  0  0  
4         0  0  1

In [184]:
sac = save_checkpoint.copy()

In [185]:
sac['Sex'] = sac['Sex'].map({'male':0,'female':1})
sac.head()

PassengerId  Pclass                                               Name  \
0            1       3                            Braund, Mr. Owen Harris   
1            2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3       3                             Heikkinen, Miss. Laina   
3            4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5       3                           Allen, Mr. William Henry   

   Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    0  22.0      1      0         A/5 21171   7.2500   NaN        S   
1    1  38.0      1      0          PC 17599  71.2833   C85        C   
2    1  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3    1  35.0      1      0            113803  53.1000  C123        S   
4    0  35.0      0      0            373450   8.0500   NaN        S   

   Survived  2  3  
0         0  0  1  
1         1  0  0  
2         1  0  1  
3         1  0  0  
4         0  0  1

In [186]:
saac_1 = save_checkpoint.copy()

In [187]:
saac_1['Sex_New'] = saac_1['Sex'].map({'male':0,'female':1})
saac_2 = saac_1.copy()
saac_1.head()

PassengerId  Pclass                                               Name  \
0            1       3                            Braund, Mr. Owen Harris   
1            2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3       3                             Heikkinen, Miss. Laina   
3            4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  2  3  Sex_New  
0         0  0  1        0  
1         1  0  0        1  
2         1  0  1        1  
3         1  0  0        1  
4         0  0  1        0

In [188]:
saac_1 = saac_1.drop(['Sex','Name'],axis  = 1)
saac_1.head()

PassengerId  Pclass   Age  SibSp  Parch            Ticket     Fare Cabin  \
0            1       3  22.0      1      0         A/5 21171   7.2500   NaN   
1            2       1  38.0      1      0          PC 17599  71.2833   C85   
2            3       3  26.0      0      0  STON/O2. 3101282   7.9250   NaN   
3            4       1  35.0      1      0            113803  53.1000  C123   
4            5       3  35.0      0      0            373450   8.0500   NaN   

  Embarked  Survived  2  3  Sex_New  
0        S         0  0  1        0  
1        C         1  0  0        1  
2        S         1  0  1        1  
3        S         1  0  0        1  
4        S         0  0  1        0

In [189]:
saac_1['Parch'].unique()

array([0, 1, 2, 5, 3, 4, 6])

In [190]:
saac_1['Ticket'].count()

891

In [191]:
saac_1.shape

(891, 13)

In [192]:
saac_1 = saac_1.drop('Ticket',axis = 1)
saac_1.head()

PassengerId  Pclass   Age  SibSp  Parch     Fare Cabin Embarked  Survived  \
0            1       3  22.0      1      0   7.2500   NaN        S         0   
1            2       1  38.0      1      0  71.2833   C85        C         1   
2            3       3  26.0      0      0   7.9250   NaN        S         1   
3            4       1  35.0      1      0  53.1000  C123        S         1   
4            5       3  35.0      0      0   8.0500   NaN        S         0   

   2  3  Sex_New  
0  0  1        0  
1  0  0        1  
2  0  1        1  
3  0  0        1  
4  0  1        0

In [193]:
embarked = saac_1['Embarked']
embarked_dummy = pd.get_dummies(embarked,drop_first=True)
saac_f = pd.concat([saac_1,embarked_dummy],axis = 1)
saac_f.head()


PassengerId  Pclass   Age  SibSp  Parch     Fare Cabin Embarked  Survived  \
0            1       3  22.0      1      0   7.2500   NaN        S         0   
1            2       1  38.0      1      0  71.2833   C85        C         1   
2            3       3  26.0      0      0   7.9250   NaN        S         1   
3            4       1  35.0      1      0  53.1000  C123        S         1   
4            5       3  35.0      0      0   8.0500   NaN        S         0   

   2  3  Sex_New  Q  S  
0  0  1        0  0  1  
1  0  0        1  0  0  
2  0  1        1  0  1  
3  0  0        1  0  1  
4  0  1        0  0  1

In [194]:
saac_f = saac_f.drop('Embarked',axis = 1)

In [195]:
saac_f.head()

PassengerId  Pclass   Age  SibSp  Parch     Fare Cabin  Survived  2  3  \
0            1       3  22.0      1      0   7.2500   NaN         0  0  1   
1            2       1  38.0      1      0  71.2833   C85         1  0  0   
2            3       3  26.0      0      0   7.9250   NaN         1  0  1   
3            4       1  35.0      1      0  53.1000  C123         1  0  0   
4            5       3  35.0      0      0   8.0500   NaN         0  0  1   

   Sex_New  Q  S  
0        0  0  1  
1        1  0  0  
2        1  0  1  
3        1  0  1  
4        0  0  1

In [196]:
saac_f['Cabin'].count()

204

In [197]:
df_with_cabin = saac_f.copy()


In [198]:
saac_f['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [199]:
saac_f  = saac_f.drop('Cabin',axis = 1)
saac_f.head()

PassengerId  Pclass   Age  SibSp  Parch     Fare  Survived  2  3  Sex_New  \
0            1       3  22.0      1      0   7.2500         0  0  1        0   
1            2       1  38.0      1      0  71.2833         1  0  0        1   
2            3       3  26.0      0      0   7.9250         1  0  1        1   
3            4       1  35.0      1      0  53.1000         1  0  0        1   
4            5       3  35.0      0      0   8.0500         0  0  1        0   

   Q  S  
0  0  1  
1  0  0  
2  0  1  
3  0  1  
4  0  1

In [200]:

saac_f2 = saac_f.copy()

In [201]:
saac_f.columns.values

array(['PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare',
       'Survived', 2, 3, 'Sex_New', 'Q', 'S'], dtype=object)

In [202]:
tmp = [ 2, 3,'Age', 'SibSp', 'Parch', 'Fare','Sex_New', 'Q',
       'S','Survived']
saac_f = saac_f[tmp]

In [203]:
saac_f.head()

2  3   Age  SibSp  Parch     Fare  Sex_New  Q  S  Survived
0  0  1  22.0      1      0   7.2500        0  0  1         0
1  0  0  38.0      1      0  71.2833        1  0  0         1
2  0  1  26.0      0      0   7.9250        1  0  1         1
3  0  0  35.0      1      0  53.1000        1  0  1         1
4  0  1  35.0      0      0   8.0500        0  0  1         0

In [204]:
saac_f.to_csv('non_standardised.csv',index = False)

In [205]:
df_standardisation1 = saac_f.iloc[:,2]
df_standardisation2 = saac_f.iloc[:,5]
new_df_combined = pd.concat([df_standardisation1,df_standardisation2],axis = 1)
new_df_combined.head()

Age     Fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [206]:
from sklearn.preprocessing import StandardScaler

In [207]:
scaler = StandardScaler()

In [208]:
scaler.fit(new_df_combined)
# stnd_df = scaler.transform(new_df_combined)

StandardScaler()

In [209]:
stnd_df = scaler.transform(new_df_combined)

In [210]:
stnd_df.shape

(891, 2)

In [211]:
data = stnd_df.shape[0]
# dfage = pd.DataFrame(data,columns='Age')
# dfage.head()
data

891

In [212]:
stnd_df

array([[-0.53037664, -0.50244517],
       [ 0.57183099,  0.78684529],
       [-0.25482473, -0.48885426],
       ...,
       [        nan, -0.17626324],
       [-0.25482473, -0.04438104],
       [ 0.15850313, -0.49237783]])

In [213]:
data_age_fare = pd.DataFrame({'Age_new':stnd_df[:,0],'Fare_new':stnd_df[:,1]})
data_age_fare.head()

Age_new  Fare_new
0 -0.530377 -0.502445
1  0.571831  0.786845
2 -0.254825 -0.488854
3  0.365167  0.420730
4  0.365167 -0.486337

In [214]:
saac_f = pd.concat([saac_f,data_age_fare],axis = 1)
saac_f.head()


2  3   Age  SibSp  Parch     Fare  Sex_New  Q  S  Survived   Age_new  \
0  0  1  22.0      1      0   7.2500        0  0  1         0 -0.530377   
1  0  0  38.0      1      0  71.2833        1  0  0         1  0.571831   
2  0  1  26.0      0      0   7.9250        1  0  1         1 -0.254825   
3  0  0  35.0      1      0  53.1000        1  0  1         1  0.365167   
4  0  1  35.0      0      0   8.0500        0  0  1         0  0.365167   

   Fare_new  
0 -0.502445  
1  0.786845  
2 -0.488854  
3  0.420730  
4 -0.486337

In [215]:
saac_f = saac_f.drop(['Age','Fare'],axis = 1)
saac_f.head()

2  3  SibSp  Parch  Sex_New  Q  S  Survived   Age_new  Fare_new
0  0  1      1      0        0  0  1         0 -0.530377 -0.502445
1  0  0      1      0        1  0  0         1  0.571831  0.786845
2  0  1      0      0        1  0  1         1 -0.254825 -0.488854
3  0  0      1      0        1  0  1         1  0.365167  0.420730
4  0  1      0      0        0  0  1         0  0.365167 -0.486337

In [216]:
saac_f.columns.values

array([2, 3, 'SibSp', 'Parch', 'Sex_New', 'Q', 'S', 'Survived', 'Age_new',
       'Fare_new'], dtype=object)

In [217]:
arr_t =[ 2, 3, 'SibSp', 'Parch', 'Sex_New', 'Q', 'S','Age_new','Fare_new','Survived']
final = saac_f[arr_t]
final.head()

2  3  SibSp  Parch  Sex_New  Q  S   Age_new  Fare_new  Survived
0  0  1      1      0        0  0  1 -0.530377 -0.502445         0
1  0  0      1      0        1  0  0  0.571831  0.786845         1
2  0  1      0      0        1  0  1 -0.254825 -0.488854         1
3  0  0      1      0        1  0  1  0.365167  0.420730         1
4  0  1      0      0        0  0  1  0.365167 -0.486337         0

In [218]:
final['Age_new'].unique()

array([-0.53037664,  0.57183099, -0.25482473,  0.36516706,         nan,
        1.67403863, -1.90813618, -0.18593675, -1.08148046, -1.77036023,
        1.94959054, -0.6681526 ,  0.64071897,  1.74292661,  0.08961515,
        0.29627909, -1.01259248, -0.11704878, -1.49480832, -0.73704057,
        0.70960695,  2.50069435,  0.8473829 , -0.59926462, -0.80592855,
       -1.83924821, -1.5636963 ,  1.32959874, -0.0481608 ,  2.43180638,
       -0.08260479, -1.70147225, -1.28814439,  1.05404683, -0.87481653,
        0.15850313, -0.9437045 , -0.32371271, -1.98873512,  0.02072718,
        0.22739111, -0.46148866, -0.39260069,  1.12293481,  2.01847851,
        2.84513424,  0.50294302,  1.19182279, -1.04703647,  2.81069025,
        0.19294712, -1.21925641, -1.42592034,  0.46849903,  1.4673747 ,
        1.77737059,  0.74405094,  0.98515886, -1.97702416,  2.15625447,
        1.81181458,  1.39848672,  0.43405504,  1.08849082, -0.63370861,
        2.22514245,  0.77849493,  1.53626267,  2.29403042, -0.42

In [219]:
final['Age_new'].mode()

0   -0.392601
dtype: float64

In [220]:
final_checkpoint = final.copy()

In [221]:
final['Age_new'] = final['Age_new'].map({'nan':-0.392601})
final.head()

2  3  SibSp  Parch  Sex_New  Q  S  Age_new  Fare_new  Survived
0  0  1      1      0        0  0  1      NaN -0.502445         0
1  0  0      1      0        1  0  0      NaN  0.786845         1
2  0  1      0      0        1  0  1      NaN -0.488854         1
3  0  0      1      0        1  0  1      NaN  0.420730         1
4  0  1      0      0        0  0  1      NaN -0.486337         0

In [222]:
final_checkpoint_2 = final_checkpoint.copy()

In [223]:
final = final_checkpoint.copy()

In [224]:
final.head()

2  3  SibSp  Parch  Sex_New  Q  S   Age_new  Fare_new  Survived
0  0  1      1      0        0  0  1 -0.530377 -0.502445         0
1  0  0      1      0        1  0  0  0.571831  0.786845         1
2  0  1      0      0        1  0  1 -0.254825 -0.488854         1
3  0  0      1      0        1  0  1  0.365167  0.420730         1
4  0  1      0      0        0  0  1  0.365167 -0.486337         0

In [225]:
final['Age_new'] = final['Age_new'].fillna(final['Age_new'].mean())
final['Fare_new'] = final['Fare_new'].fillna(final['Fare_new'].mean())

In [226]:
final_processed = final.copy()

In [227]:
final_processed.to_csv('processed.csv',index = False)

In [228]:
inputs = final.iloc[:,0:9]
inputs.head()

2  3  SibSp  Parch  Sex_New  Q  S   Age_new  Fare_new
0  0  1      1      0        0  0  1 -0.530377 -0.502445
1  0  0      1      0        1  0  0  0.571831  0.786845
2  0  1      0      0        1  0  1 -0.254825 -0.488854
3  0  0      1      0        1  0  1  0.365167  0.420730
4  0  1      0      0        0  0  1  0.365167 -0.486337

In [229]:
targets = final['Survived']
targets.sum()/891

0.3838383838383838

In [230]:
final.shape

(891, 10)

## solving  with balancing and shuffling 

In [236]:
target_sum = int(np.sum(targets))
target_sum

342

In [258]:
list_to_emp = []
counter_0 = 0
for i in range(targets.shape[0]):
    if targets[i]==0:
        counter_0= counter_0+1
        if counter_0>target_sum:
           list_to_emp.append(i)

In [266]:
# inputs_balanced = inputs.drop(inputs,list_to_emp,axis = 0)
# targets_balanced 
inputs_1 = inputs.copy()
targets_1 = targets.copy()
inputs_balanced = inputs.drop(index = list_to_emp,axis = 0)
target_balanced = targets.drop(index = list_to_emp,axis = 0)

In [270]:
target_balanced.sum()/target_balanced.shape[0]

0.5

## shuffling

In [252]:
# index = np.arange(targets.shape[0])
# # index
# np.random.shuffle(index)

# shuffled_inputs = inputs[index]
# shuffle_targets  = targets[index]

## modelling

In [272]:
from sklearn.linear_model import LogisticRegression


In [273]:
model = LogisticRegression()

In [274]:
model.fit(inputs_balanced,target_balanced)

LogisticRegression()

In [275]:
model.score(inputs_balanced,target_balanced)

0.7748538011695907

In [276]:
model.coef_

array([[-0.71032919, -1.76357669, -0.3753789 ,  0.09517641,  2.42218265,
         0.13096848, -0.4192417 , -0.48462328,  0.05950202]])

In [277]:
model.intercept_

array([0.52319093])

## summary table

In [279]:
arr = inputs_balanced.columns.values

In [280]:
arr

array([2, 3, 'SibSp', 'Parch', 'Sex_New', 'Q', 'S', 'Age_new', 'Fare_new'],
      dtype=object)

In [283]:
summary_table = pd.DataFrame(columns = ['Features'],data = arr)
summary_table

Features
0         2
1         3
2     SibSp
3     Parch
4   Sex_New
5         Q
6         S
7   Age_new
8  Fare_new

In [284]:
summary_table['coefficient'] = np.transpose(model.coef_)
summary_table

Features  coefficient
0         2    -0.710329
1         3    -1.763577
2     SibSp    -0.375379
3     Parch     0.095176
4   Sex_New     2.422183
5         Q     0.130968
6         S    -0.419242
7   Age_new    -0.484623
8  Fare_new     0.059502

In [286]:
summary_table.index = summary_table.index+1
summary_table.loc[0] = ['Intercept',model.intercept_[0]]
summary_table  = summary_table.sort_index()
summary_table

Features  coefficient
0  Intercept     0.523191
1          2    -0.710329
2          3    -1.763577
3      SibSp    -0.375379
4      Parch     0.095176
5    Sex_New     2.422183
6          Q     0.130968
7          S    -0.419242
8    Age_new    -0.484623
9   Fare_new     0.059502

In [288]:
## using the  numpy exp to measure the different coeficient
summary_table['odds_ratio'] = np.exp(summary_table.coefficient)
summary_table

Features  coefficient  odds_ratio
0  Intercept     0.523191    1.687403
1          2    -0.710329    0.491482
2          3    -1.763577    0.171431
3      SibSp    -0.375379    0.687029
4      Parch     0.095176    1.099853
5    Sex_New     2.422183   11.270432
6          Q     0.130968    1.139932
7          S    -0.419242    0.657545
8    Age_new    -0.484623    0.615929
9   Fare_new     0.059502    1.061308

## table acc to significance of the features

In [291]:
summary_table.sort_values('odds_ratio',ascending = False)

Features  coefficient  odds_ratio
5    Sex_New     2.422183   11.270432
0  Intercept     0.523191    1.687403
6          Q     0.130968    1.139932
4      Parch     0.095176    1.099853
9   Fare_new     0.059502    1.061308
3      SibSp    -0.375379    0.687029
7          S    -0.419242    0.657545
8    Age_new    -0.484623    0.615929
1          2    -0.710329    0.491482
2          3    -1.763577    0.171431

## testing the model

In [296]:
test_raw_data = pd.read_csv('test_modifies.csv')
test_raw_data

0  1 -8.987324e-02 -1.724051e-01
120  1  0      0      0        1  0  1 -1.290452e+00 -3.559637e-01
121  0  1      1      0        0  1  0  4.280378e-17 -4.992288e-01
122  0  0      1      0        1  0  0  3.338605e-01  3.961786e-01
123  0  1      0      0        0  0  1 -1.604955e-01 -5.081829e-01
124  0  1      0      0        0  1  0  4.280378e-17 -4.992288e-01
125  0  1      0      1        1  0  1 -9.373407e-01 -3.496958e-01
126  0  1      0      0        0  0  1 -5.842293e-01 -4.984087e-01
127  0  1      2      0        1  1  0  4.280378e-17 -2.216525e-01
128  1  0      0      0        0  0  1  8.282165e-01 -4.052111e-01
129  0  1      0      0        0  0  1 -4.429847e-01 -4.938564e-01
130  0  1      0      0        0  0  1  1.219936e-01 -4.938564e-01
131  0  0      0      0        0  0  0  1.605062e+00 -1.276348e-01
132  0  1      0      4        1  0  1  4.280378e-17 -1.819555e-01
133  0  1      1      0        0  0  0  4.280378e-17 -5.227333e-01
134  0  1      0      0        0  0  1  8.988388e-01 -4.966178e-01
135  0  1      0      0        0  0  1 -4.429847e-01 -4.973628e-01
136  0  1      0      0        0  0  0 -2.664290e-01 -5.086306e-01
137  1  0      0      0        0  0  1 -3.017401e-01 -4.052111e-01
138  0  1      0      0        1  0  1 -5.136070e-01 -4.938564e-01
139  0  1      1      6        0  0  1  6.869719e-01  2.018752e-01
140  0  1      5      2        1  0  1 -1.431697e+00  2.018752e-01
141  0  0      0      0        1  0  1  1.926159e-01  2.075963e+00
142  0  0      1      3        0  0  0  2.170040e+00  4.060634e+00
143  1  0      0      0        0  0  1 -1.604955e-01 -1.724051e-01
144  0  0      0      0        0  0  1  8.282165e-01 -1.625556e-01
145  0  1      3      0        0  0  1  5.137133e-02 -3.156703e-01
146  0  0      0      0        0  0  1  4.280378e-17  2.907444e-01
147  0  1      0      0        0  0  1 -5.842293e-01 -4.938564e-01
148  0  0      0      0        0  0  1  4.280378e-17 -1.625556e-01
149  1  0      1      1        0  0  1 -1.925095e-02 -1.724051e-01
150  0  0      0      1        1  0  0 -5.136070e-01  8.511942e-01
151  0  1      0      0        0  0  0  4.280378e-17 -4.966178e-01
152  0  1      0      0        0  0  1  2.134729e+00 -5.258251e-17
153  0  1      0      2        1  0  1  4.044828e-01 -4.198366e-01
154  0  1      4      2        0  0  1 -1.219830e+00 -7.592497e-02
155  0  1      0      0        0  0  1 -4.429847e-01 -5.028105e-01
156  0  0      0      0        1  0  1 -8.987324e-02  3.333638e+00
157  0  1      0      0        1  0  1 -5.136070e-01 -4.973628e-01
158  0  0      0      0        0  0  1  8.282165e-01 -1.625556e-01
159  0  1      0      2        1  0  1 -3.017401e-01 -3.913322e-01
160  0  1      0      0        1  1  0  4.280378e-17 -4.995279e-01
161  0  1      1      1        0  0  0 -1.643564e+00 -3.649929e-01
162  1  0      0      0        1  0  1 -3.017401e-01 -3.962570e-01
163  0  1      0      0        0  0  1  4.280378e-17 -5.126600e-01
164  1  0      0      0        0  0  1  7.575942e-01 -4.052111e-01
165  0  1      1      1        1  0  1 -3.017401e-01 -2.435900e-01
166  0  0      0      0        0  0  0  1.251950e+00  2.662693e-01
167  0  1      2      2        0  0  1 -8.667184e-01 -2.242438e-02
168  0  0      0      0        1  0  0  4.280378e-17 -1.415888e-01
169  0  1      0      0        1  0  1 -5.842293e-01 -4.775152e-01
170  0  1      0      0        0  0  1  4.280378e-17 -5.028105e-01
171  0  1      0      0        0  0  0 -2.311178e-01 -5.086306e-01
172  0  1      1      0        0  0  1 -5.136070e-01 -3.890937e-01
173  0  1      0      0        0  0  0  4.280378e-17 -5.085554e-01
174  0  1      1      5        0  0  1  6.869719e-01 -7.592497e-02
175  1  0      0      2        1  0  1 -1.078585e+00  6.040081e-02
176  1  0      0      0        1  0  1 -7.254738e-01  2.010748e-02
177  0  0      1      0        0  0  0  1.675684e+00  3.548412e-01
178  1  0      0      3        1  0  1  4.044828e-01  6.040081e-02
179  0  0     

In [297]:
predict_outcome = model.predict_proba(test_raw_data)

In [298]:
predict_outcome

array([[0.78308267, 0.21691733],
       [0.55374828, 0.44625172],
       [0.76308852, 0.23691148],
       [0.8286877 , 0.1713123 ],
       [0.32286996, 0.67713004],
       [0.7559917 , 0.2440083 ],
       [0.21547036, 0.78452964],
       [0.67861494, 0.32138506],
       [0.17199287, 0.82800713],
       [0.89141325, 0.10858675],
       [0.84411593, 0.15588407],
       [0.60935053, 0.39064947],
       [0.07948561, 0.92051439],
       [0.89207557, 0.10792443],
       [0.16721752, 0.83278248],
       [0.11245348, 0.88754652],
       [0.56039612, 0.43960388],
       [0.72177715, 0.27822285],
       [0.38469608, 0.61530392],
       [0.3435568 , 0.6564432 ],
       [0.6622097 , 0.3377903 ],
       [0.70494893, 0.29505107],
       [0.07433508, 0.92566492],
       [0.27624511, 0.72375489],
       [0.07653282, 0.92346718],
       [0.93892847, 0.06107153],
       [0.03383754, 0.96616246],
       [0.73196827, 0.26803173],
       [0.56676438, 0.43323562],
       [0.88142624, 0.11857376],
       [0.

In [299]:
final_prediction = predict_outcome[:,1]

In [300]:
final_prediction

array([0.21691733, 0.44625172, 0.23691148, 0.1713123 , 0.67713004,
       0.2440083 , 0.78452964, 0.32138506, 0.82800713, 0.10858675,
       0.15588407, 0.39064947, 0.92051439, 0.10792443, 0.83278248,
       0.88754652, 0.43960388, 0.27822285, 0.61530392, 0.6564432 ,
       0.3377903 , 0.29505107, 0.92566492, 0.72375489, 0.92346718,
       0.06107153, 0.96616246, 0.26803173, 0.43323562, 0.11857376,
       0.15879892, 0.24106402, 0.61494432, 0.63750547, 0.54505618,
       0.29572758, 0.67550046, 0.74100118, 0.18138198, 0.16282045,
       0.1873117 , 0.52355177, 0.11340992, 0.85827321, 0.84087344,
       0.18113292, 0.50320658, 0.24248152, 0.8777483 , 0.6760911 ,
       0.4923061 , 0.47574968, 0.8173279 , 0.87106518, 0.44806281,
       0.13837515, 0.1357586 , 0.18108946, 0.11346623, 0.95216441,
       0.22532145, 0.33423798, 0.21937699, 0.82723617, 0.68902388,
       0.85817527, 0.8459561 , 0.38666968, 0.62028089, 0.8527474 ,
       0.8172373 , 0.20232581, 0.68494498, 0.64001595, 0.95124

In [301]:
survival_output = np.where(final_prediction>0.5,1,0)
survival_output

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,

In [302]:
df_output = pd.DataFrame({'Survived':survival_output})
df_output.head()

Survived
0         0
1         0
2         0
3         0
4         1

In [305]:
df_oo = pd.read_csv('test.csv')
df_oo.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [307]:
df_id = df_oo.iloc[:,0]

In [308]:
final_csv  =  pd.concat([df_id,df_output],axis = 1)
final_csv.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

In [311]:
prediction_output =  final_csv.to_csv('output_2.csv',index = False)

In [ ]:
ooo = read.csv